# Generated by Django 6.0.8 on 2026-08-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='searches', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_offers', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_offers', to='flights.airport')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='flights.flightsearch')),
            ],
        ),
    ]
